var redStations = [
    "PED/walkthru gate",
    "AV/CPX Gate",
    "1-17 CAV, P-860",
    "4-2 ARB S-869",
    "New Dental Clinic",
    "AV/CPX Gate",
    "Bus Terminal",
    "Lodging S-121",
    "USO S-375",
    "Quarry Gate",
    "2nd CAB/CDC",
    "Medical/Dental Clinic",
    "Super Gym",
    "School",
    "New Commissary",
    "New PX",
    "One Stop Bldg",
    "One Stop Bldg A",
    "Tomahawk DFAC",
    "VMF S-7412",
    "VMF S-7515",
    "HQs P-7621",
    "VMF S-7515",
    "VMF S-7412",
    "Tomahawk DFAC",
    "Spartan DFAC S6321",
    "Bldg # P-6315",
    "Chapel P-6360",
    "New Barracks P-6001",
    "Talon DFAC S-2097",
    "3rd MI Bn",
    "TMP P-7010",
    "ROKA HQs",
    "8th Army HQs",
    "S-12114",
    "Provider DFAC S1291",
    "Zoeckler station S1210",
    "PED/walkthru gate",
];

var greenStations = [
    "Bus Terminal",
    "Medical Clinic",
    "USO S-375",
    "Super Gym",
    "School",
    "Talon DFAC S-2097",
    "3rd MI Bn",
    "New Barracks P-6001",
    "Chapel P-6360",
    "Bldg # P-6315",
    "Spartan DFAC S6321",
    "One Stop",
    "New Commissary",
    "New PX",
    "Warrior Zone S 6813",
    "Spartan DFAC S6321",
    "Bldg # P-6315",
    "Chapel P-6360",
    "New Barracks P-6001",
    "3rd MI Bn",
    "Talon DFAC S-2097",
    "School",
    "Super Gym",
    "USO S-375",
    "Medical Clinic",
    "Bus Terminal",
    "CPX",
    "Walkthru gate",
    "Zoeckler station S-1210",
    "Provider Grill S-1291",
    "Zoeckler station S-1210",
    "Walkthru gate",
    "CPX",
    "Bus Terminal",
];

var blueStations = [
    "PED/walkthru gate",
    "Zoeckler station S1210",
    "Provider DFAC S1291",
    "S-12114",
    "8th Army HQs",
    "ROKA HQs",
    "TMP P-7010",
    "3rd MI Bn",
    "Talon DFAC S-2097",
    "New Barracks P-6001",
    "Chapel P-6360",
    "Bldg # P-6315",
    "Spartan DFAC S6321",
    "Tomahawk DFAC",
    "VMF S-7412",
    "VMF S-7515",
    "HQs P-7621",
    "VMF S-7515",
    "VMF S-7412",
    "Tomahawk DFAC",
    "One Stop Bldg A",
    "One Stop Bldg",
    "New PX",
    "New Commissary",
    "School",
    "Super Gym",
    "Quarry Gate",
    "2nd CAB/CDC",
    "Medical/Dental Clinic",
    "USO S-375",
    "Lodging S-121",
    "Bus Terminal",
    "AV/CPX Gate",
    "1-17 CAV, P-860",
    "4-2 ARB S-869",
    "New Dental Clinic",
    "AV/CPX Gate",
    "PED/walkthru gate",
];
